services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: tpg_user
      POSTGRES_PASSWORD: tpg_password
      POSTGRES_DB: tpg_repo
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data