services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: gabosawn
      POSTGRES_PASSWORD: 140703
      POSTGRES_DB: ledger_repo
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data