services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: tpg_user
      POSTGRES_PASSWORD: tpg_password
      POSTGRES_DB: tpg_repo
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data

  web-server:
    build: .
    environment:
      MIX_ENV: docker_config
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./lib:/app/lib
      - ./config:/app/config
  cover-server:
    image: nginx:alpine
    container_name: cover-reports
    ports:
      - "8080:80"
    volumes:
      - ./cover:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped